### PR TITLE
Pkdotnet

### PR DESCRIPTION
**Pull request by preetikrp**
## Status
Choose:
**HOLD**

## Migrations
YES

## Description
I have created an Order model (Order.cs) in order to create a table in the database for Orders. I also created an order controller(OrderController.cs) to Get (read) list of all orders, Get a single specific order, Post(create) an order, Put(update) a specific order, and Delete a specific order. I have also modified BangazonApIContext file to set up a relationship between the database and order table. Also created a model builder to generate time-stamp for when an order is created. 

I also made following changes -
1. Changed Icollection customer to order to show multiple orders in the collection.
2. Corrected the spelling on DateOrderd to DateOrderedIn in Order.cs line 19. 

## Todos
- [x] Tests
- [x] Documentation

## Deploy Notes
Not deployed

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```sh
I have set following methods: GET, POST, PUT, DELETE

Follow below steps to test

git fetch --a  (fetch all branches from GitHub)
git branch -avv (display all branches)
git checkout pkdotnet (switch into my branch)
git pull origin pkdotnet (pull my code down to test)
dotnet ef migrations add Initial (migrations need to be built)
dotnet ef database update (update the database since a new migration has been built)
open bangazon.db (open database)
dotnet run

Make sure to have Postman installed: https://www.getpostman.com/
In Postman, 'Post' (add) few sample order before testing.
Also, make sure http://localhost:5000/ is running

Example:
{
    "PayTypeId": 4,
	"DateOrdered": "07/27/2017 9:45:06 PM",
	"CustomerId": 1,
	"Customer": "Preeti"
}

To view all products:
Select GET
http://localhost:5000/api/order

To view a single product:
Select GET
http://localhost:5000/api/order/{id}

To edit a single product
Select PUT
http://localhost:5000/api/order/{id}

To delete a single product
Select DELETE
http://localhost:5000/api/order/{id}

```

## Impacted Areas in Application
List general components of the application that this PR will affect:

* Models\Order.cs
* Controllers\OrderController.cs

### CODE REVIEW

**Comment by krissycaron** [comment]
@preetikrp Please go back through and create a comment on your classes and  methods to document the purpose and functionality of each one. Like the following : 
//PK- Created this Controller to get, post, add, delete the Orders 

and then on each method: 
example: [HttpPut("{id}")]
        public IActionResult Put(int id, [FromBody] Order order)
comment // This Put will update the orderid , if an order id is not found it returns a bad request. if the orderid is found then it will update the orderId.


Also in your Order.cs on line 19 please correct the spelling on DateOrderd to DateOrdered 

and confirm with @Kmille15 on the class name for payTypeId?

**Comment by Kmille15** [comment]
Post, Put, Get, and Delete are working.

**Comment by preetikrp** [comment]
Added comments. Corrected the spelling.

**Comment by krissycaron** [comment]
I have pulled this branch down and tested the Get, Post, Put and Delete  for the orders table. It is all working correctly. @preetikrp  Maybe in the Order.cs in the model, change the customerId variable to match the one we established in the Customer.cs Model of CustomerId variable. I am not sure i t will effect the code, but just so the code is smooth and readable.

**Pull request merged**
